name: Build and Test (Windows Only)

on:
  push:
    branches-ignore:
      - main
      - master
  pull_request:

jobs:
  build:
    name: Build (Windows Only)
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore the solution
        run: dotnet restore ./WSyncPro.sln

      - name: Build the solution for Windows
        run: dotnet build ./WSyncPro.App/WSyncPro.App.csproj -c Release -f net8.0-windows10.0.19041.0 --no-restore

  test:
    name: Test (Windows Only)
    runs-on: windows-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore the solution
        run: dotnet restore ./WSyncPro.sln

      - name: Build the test project
        run: dotnet build ./WSyncPro.Test/WSyncPro.Test.csproj -c Debug

      - name: Run tests
        run: dotnet test ./WSyncPro.Test/WSyncPro.Test.csproj --verbosity normal
